# Generated by Django 4.2.2 on 2024-01-09 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=100)),
                ('links', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('pub_date', models.DateField(default='')),
                ('image', models.ImageField(default='', upload_to='MoviesHub/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoviesHub.category')),
            ],
        ),
    ]
