# Generated by Django 4.0.6 on 2024-02-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesHub', '0003_category_slug_moviecard_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='c_slug',
        ),
        migrations.RenameField(
            model_name='moviecard',
            old_name='slug',
            new_name='m_slug',
        ),
    ]
